services:
  fedora43-ai:
    build:
      context: .
      dockerfile: Containerfile
    image: localhost/fedora43-ai:latest
    container_name: ${INSTANCE:-fedora43-ai}

    cap_add:
      - NET_ADMIN
      - NET_RAW

    devices:
      - /dev/net/tun

    #security_opt:
    #  - label=disable

    #tmpfs:
    #  - /tmp
    #  - /run
    #  - /run/lock

    ports:
      - "127.0.0.1:11000:11000"
      - "127.0.0.1:11001:11001"
      - "127.0.0.1:10999:10999"
      - "127.0.0.1:11002:11002"

    env_file:
      - .env

    environment:
      - PATH=/usr/local/bin:/root/.local/bin:/root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - DISPLAY=${DISPLAY:-:0}
      - NO_AT_BRIDGE=1
      - XDG_RUNTIME_DIR=/tmp/runtime-root
      - HERMES_HOME=/root/hermes-home
      - HERMES_INSTALL_DIR=/usr/local/lib/hermes-agent
      - OPENCLAW_START=1
      - HERMES_START=1

    volumes:
      - ${HOST_HOME_DIR:-home}:/home
      - ${HOST_SRV_DIR}:/srv
      - ${HOST_ROOT_DIR:-root}:/root
      - ${HOST_TAILSCALE_DIR:-tailscale}:/var/lib/tailscale
      - /tmp/.X11-unix:/tmp/.X11-unix

volumes:
  home:
  root:
  tailscale:
