services:
  fedora43-ai-f24:
    image: localhost/fedora43-ai:latest
    container_name: fedora43-ai-f24
    command: sleep infinity
    volumes:
      - fedora43-ai-f24_home:/home
      - fedora43-ai-f24_srv:/srv
      - fedora43-ai-f24_opt:/opt

volumes:
  fedora43-ai-f24_home:
  fedora43-ai-f24_srv:
  fedora43-ai-f24_opt:
